version: '3'

services:
  # FastAPI service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: 
      - .env 
    volumes:
      - .:/app  

  # # Redis service
  # redis:
  #   image: redis:latest 
  #   ports:
  #     - "6379:6379"
