services:
  # FastAPI service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app
